ktor {
    deployment {
        port = 8080
        port = ${?SERVER_PORT}
    }
    application {
        modules = [ com.magazines.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/magazines_catalog"
    url = ${?DATABASE_URL}
    user = "app"
    user = ${?DATABASE_USER}
    password = "app_password"
    password = ${?DATABASE_PASSWORD}
}

storage {
    path = "./storage"
    path = ${?STORAGE_PATH}
}

firebase {
    credentialsPath = "src/main/resources/firebase-service-account.json"
    credentialsPath = ${?FIREBASE_CREDENTIALS_PATH}
}
