ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.magazines.HttpKt.configureHttp
      - com.magazines.SerializationKt.configureSerialization
      - com.magazines.SecurityKt.configureSecurity
      - com.magazines.StatusPagesKt.configureStatusPages
      - com.magazines.RoutingKt.configureRouting
